using Newtonsoft.Json;

namespace LibreOpenAI.OpenAi.ChatAi.CompletionsAi.Requests.Messages.Conents
{
    public interface IMessageContentType
    {
        /// <summary>
        /// The type of the content part.
        /// </summary>
        /// <remarks>Required</remarks>
        [JsonProperty("type")]
        [JsonRequired]
        string Type { get; set; }
        /// <summary>
        /// The refusal message generated by the model.
        /// </summary>
        /// <remarks>Required only when Type = "refusal"</remarks>
        [JsonProperty("refusal")]
        string? Refusal { get; set; }
        /// <summary>
        /// The text content.
        /// </summary>
        /// <remarks>Required only when Type = "text"</remarks>
        [JsonProperty("text")]
        string? Text { get; set; }
        /// <summary>
        /// The image_url object is Required
        /// </summary>
        /// <remarks>Required only when Type = "image_url"</remarks>
        [JsonProperty("image_url")]
        [JsonRequired]
        IImageUrlContent? ImageUrl { get; set; }
        /// <summary>
        /// The input_audio object is Required
        /// </summary>
        /// <remarks>Required only when Type = "input_audio"</remarks>
        [JsonProperty("input_audio")]
        [JsonRequired]
        IInputAudioContent? InputAudio { get; set; }
    }
}
