using Newtonsoft.Json;

namespace LibreOpenAI.OpenAi.ChatAi.CompletionsAi.Requests.Messages.Conents
{
    public interface IRefusalContentPart
    {
        /// <summary>
        /// The refusal message generated by the model.
        /// </summary>
        /// <remarks>Required</remarks>
        [JsonProperty("refusal")]
        [JsonRequired]
        string Refusal { get; set; }
    }
}