using Newtonsoft.Json;

namespace LibreOpenAI.OpenAi.ChatAi.CompletionsAi.Response.Usage.CompletionTokensDetails
{
    public interface ICompletionTokensDetailsResponse
    {
        /// <summary>
        /// Tokens generated by the model for reasoning.
        /// </summary>
        [JsonProperty("reasoning_tokens")]
        int ReasoningTokens { get; set; }
    }
}