name: Publish NuGet Package

on:
  release:
    types: [published]  # Triggers the action when a new release is published on GitHub.

jobs:
  publish:
    runs-on: ubuntu-latest  # The action runs on a Linux machine.

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup .NET 8 to run .NET CLI commands.
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Set the version of .NET to 8.x.

      # Step 3: Build the project.
      - name: Build solution
        run: dotnet build --configuration Release

      # Step 4: Create the NuGet package.
      - name: Pack NuGet package
        run: dotnet pack --configuration Release

      # Step 5: Publish the package to nuget.org.
      - name: Publish to NuGet
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
